language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

script:
  - make travis
  - ls -l bin

deploy:
  provider: releases
  api_key:
    secure: UuDzRyO36GwQuZvud9QnMURKrd4rmPRYfImDyjeeaO7yge+I4McAXVuyp21AGq0EC+yesu+SEm/0KRy3VEsapnfMdmx4EnaqnfbTLjojTKkunzcEQEZ+pOacviehxd01OvBZTzNqZ18/HFTfAezxp6iqm5ppMEWVXDUqG4Mo/XIJVrE+P8KpfSfsGO+JvPp5mJ69ggGC56iR0mUdaYH6F/+OXQrrEJG7B3utcvwEp3bOazVWsSrucBehjnBWVhubCu10btTycBqr2vQIK3Gs0QTNJtSyYZ5iCfSp3sZeGCy25BNR+78YEt+XaEGHySYyHzPbzEMw5jjQFpSTd1a4jDU0Bx+xBqYotj9rzH2OHv3uutJtOLZfuF6QWwKyy92HiGRuM0njw1DYTSd+lCMGI292kQoZVecUR4Z7PhMEiM0C0MD8tDbZ+Nz3xII1DNA3EffqDykriGlJwK0MEEpm4uAF9eOd4KgZBdPIYq30zLiV3lnzcPEH5n76AxIcRPkz33IKHeNC29e3ussppOCua9+6R7fQt8en4z5uF8EkNiwCV99nKUcAdJM1CYu+OtwyPEWmK2vg5kQFTW+7uBhOszm7fe3RpzGi0DeIwltLBdV97cD21z+rJV9EzdCwTjdV+5DkciMvabNvhEr7P8v8E5BAAAAu0mGmrQx1einnDUM=
  skip_cleanup: true
  file:
    - bin/public-strategies-darwin.${TRAVIS_TAG}.tar.gz
    - bin/public-strategies-linux.${TRAVIS_TAG}.tar.gz
    - bin/public-strategies-windows.${TRAVIS_TAG}.zip
  on:
    repo: VEuPathDB/script-public-strategy-runner
    tags: true